name: Volunteer Submission
description: Submit your availability for volunteering
title: "[Volunteer Sign Up] <Event Name>"
labels: [volunteer-submission]
body:
  - type: input
    id: name
    attributes:
      label: Full Name
      description: Please enter your full name
      placeholder: John Doe
    validations:
      required: true

  - type: input
    id: phone
    attributes:
      label: Phone Number
      description: Enter your phone number including country code to receive SMS notification reminder beforehand
      placeholder: "+1234567890"
    validations:
      required: false

  - type: textarea
    id: shifts
    attributes:
      label: What shifts are you available for?
      description: >
        Enter each shift on a new line in a readable format like:

        Monday July 22, 2025, 6:00 PM – Usher  
        Saturday July 27, 2025, 9:00 AM – Greeter
      placeholder: "e.g. Monday July 22, 2025, 6:00 PM – Usher"
    validations:
      required: true
