name: Volunteer Submission
description: Submit your availability for volunteering
title: "[Volunteer] <Your Name>"
labels: [volunteer-submission]
body:
  - type: input
    id: name
    attributes:
      label: Full Name
      description: Please enter your full name
      placeholder: John Doe
    validations:
      required: true

  - type: input
    id: phone
    attributes:
      label: Phone Number
      description: Enter your phone number including country code
      placeholder: +1234567890
    validations:
      required: true

  - type: textarea
    id: shifts
    attributes:
      label: What shifts are you available for?
      description: >
        Enter each shift on a new line in a readable format like:

        Monday July 22, 6:00 PM – Usher
        Saturday July 27, 9:00 AM – Greeter
      placeholder: "e.g. Monday July 22, 6:00 PM – Usher"
    validations:
      required: true
