name: Volunteer Submission
description: Submit your availability for volunteering
title: "[Volunteer] <Your Name>"
labels: [volunteer-submission]
body:
  - type: input
    id: name
    attributes:
      label: Full Name
      description: Please enter your full name
      placeholder: Jane Doe
    validations:
      required: true

  - type: input
    id: phone
    attributes:
      label: Phone Number
      description: Include area or country code (e.g. +1 or +44)
      placeholder: +1234567890
    validations:
      required: true

  - type: textarea
    id: availability
    attributes:
      label: What shifts are you available for?
      description: |
        Tell us the days and times you can volunteer.
        Include any preferred roles (e.g. Usher, Greeter, etc.)
      placeholder: |
        Example:
        - Monday July 22, 6:00 PM — Usher
        - Saturday July 27, 9:00 AM — Greeter
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Any other notes?
      description: Optional: Tell us anything else we should know.
      placeholder: (Optional) Allergies, special needs, or role preferences
    validations:
      required: false
