name: Volunteer Submission
description: Submit your availability for volunteering
title: "[Volunteer Sign Up] <Event Name>"
labels: [volunteer-submission]
body:
  - type: input
    id: name
    attributes:
      label: Full Name
      description: Please enter your full name
      placeholder: John Doe
    validations:
      required: true

  - type: input
    id: phone
    attributes:
      label: Phone Number
      description: Enter your phone number including country code to receive SMS notification reminder beforehand (optional)
      placeholder: "+1234567890"

  - type: dropdown
    id: notify_sms
    attributes:
      label: Notify me via SMS
      description: Would you like to receive SMS reminders for your shifts?
      options:
        - "Yes"
        - "No"

  - type: textarea
    id: shifts
    attributes:
      label: What shifts are you available for?
      description: >
        Copy, Paste and Edit this date and time keeping the same format and enter each availability on a new line:

        Monday July 22, 2025, 6:00 PM – Usher
      placeholder: "e.g. Monday July 22, 2025, 6:00 PM – Usher"
    validations:
      required: true
