name: Process Submission

on:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest
    env:
      VOLUNTEER_NAME: "John Doe"
      VOLUNTEER_PHONE: "+1234567890"
      VOLUNTEER_SHIFTS: '[{"date": "2025-07-07", "time": "18:00", "role": "Usher"}, {"date": "2025-07-09", "time": "09:00", "role": "Greeter"}]'
      CLICKSEND_USERNAME: ${{ secrets.CLICKSEND_USERNAME }}
      CLICKSEND_API_KEY: ${{ secrets.CLICKSEND_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process volunteer submission
        run: |
          python volunteer_schedule.py \
            --name "$VOLUNTEER_NAME" \
            --phone "$VOLUNTEER_PHONE" \
            --shifts "$VOLUNTEER_SHIFTS" \
            --notify_sms

      - name: Generate calendar files
        run: python generate_calendar.py

      - name: Commit calendar changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/calendar.html docs/volunteer_schedule.json volunteer_input.yaml
          git commit -m "Update calendar and schedule data"
          git push
