name: Process Submission

on:
  workflow_dispatch:
  repository_dispatch:
  # Could be triggered by form submission webhook or API call

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process volunteer submission
        env:
          CLICKSEND_USERNAME: ${{ secrets.CLICKSEND_USERNAME }}
          CLICKSEND_API_KEY: ${{ secrets.CLICKSEND_API_KEY }}
        run: |
          # Example command that receives volunteer input from event payload
          # This should be adapted based on how the submission is passed in
          python volunteer_schedule.py --name "$VOLUNTEER_NAME" --phone "$VOLUNTEER_PHONE" --shifts "$VOLUNTEER_SHIFTS"

      - name: Generate calendar files
        run: python generate_calendar.py

      - name: Commit calendar changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/calendar.html docs/volunteer_schedule.json volunteer_input.yaml
          git commit -m "Update calendar and schedule data"
          git push
