name: Process All Volunteers

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml

      - name: Process all volunteers from YAML
        run: |
          python -c "import yaml, subprocess; f = open('volunteer_input.yaml'); volunteers = yaml.safe_load(f); f.close(); \
for v in volunteers: subprocess.run(['python', 'volunteer_schedule.py', '--name', v['name'], '--phone', v['phone'], '--shifts', str(v['shifts']), '--notify_sms'])"

      - name: Generate calendar files
        run: python generate_calendar.py

      - name: Copy volunteer_schedule.json to docs/
        run: |
          mkdir -p docs
          cp volunteer_schedule.json docs/volunteer_schedule.json

      - name: Commit calendar changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/calendar.html docs/volunteer_schedule.json volunteer_input.yaml
          git commit -m "Update calendar and schedule data"
          git push
