name: Process Submission

on:
  workflow_dispatch:
  repository_dispatch:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml

      - name: Parse issue and update volunteer_input.yaml
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "$ISSUE_BODY" > issue_body.txt

          python -c "
import yaml
import json

with open('issue_body.txt') as f:
    body = f.read()

def extract_field(label):
    start = body.find(f'**{label}**:') + len(f'**{label}**:')
    end = body.find('\\n', start)
    return body[start:end].strip()

name = extract_field('Full Name')
phone = extract_field('Phone Number')
shifts_json = body.split('**Shift Availability**:')[1].strip()
shifts = json.loads(shifts_json)

try:
    with open('volunteer_input.yaml') as f:
        data = yaml.safe_load(f) or []
except FileNotFoundError:
    data = []

data.append({'name': name, 'phone': phone, 'shifts': shifts})

with open('volunteer_input.yaml', 'w') as f:
    yaml.dump(data, f, sort_keys=False)
"

      - name: Commit updated volunteer_input.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add volunteer_input.yaml
          git commit -m "Append new volunteer submission"
          git push

      - name: Trigger Process All Volunteers workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: clgi-technology/volunteer-schedular
          event-type: process-all-volunteers
