name: Process All Volunteers

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml

      - name: Write Python script to process volunteers
        run: |
          echo "import yaml" > process.py
          echo "import subprocess" >> process.py
          echo "" >> process.py
          echo "with open('volunteer_input.yaml') as f:" >> process.py
          echo "    volunteers = yaml.safe_load(f)" >> process.py
          echo "" >> process.py
          echo "for v in volunteers:" >> process.py
          echo "    name = v['name']" >> process.py
          echo "    phone = v['phone']" >> process.py
          echo "    shifts = v['shifts']" >> process.py
          echo "    subprocess.run([" >> process.py
          echo "        'python', 'volunteer_schedule.py'," >> process.py
          echo "        '--name', name," >> process.py
          echo "        '--phone', phone," >> process.py
          echo "        '--shifts', str(shifts)," >> process.py
          echo "        '--notify_sms'" >> process.py
          echo "    ])" >> process.py

      - name: Run volunteer processing script
        run: python process.py

      - name: Generate calendar files
        run: python generate_calendar.py

      - name: Copy volunteer_schedule.json to docs/
        run: |
          mkdir -p docs
          cp volunteer_schedule.json docs/volunteer_schedule.json

      - name: Commit calendar changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/calendar.html docs/volunteer_schedule.json volunteer_input.yaml
          git commit -m "Update calendar and schedule data"
          git push
