name: Send Volunteer Schedule & Update Calendar

on:
  repository_dispatch:
    types: [send_volunteer_schedule]

jobs:
  send_and_update:
    runs-on: ubuntu-latest

    env:
      CLICKSEND_USERNAME: ${{ secrets.CLICKSEND_USERNAME }}
      CLICKSEND_API_KEY: ${{ secrets.CLICKSEND_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install clicksend-client PyYAML

      - name: Parse input and send SMS
        run: |
          python volunteer_schedule.py --name "${{ github.event.client_payload.name }}" \
            --phone "${{ github.event.client_payload.phone }}" \
            --shifts "${{ github.event.client_payload.shifts }}"
          
      - name: Generate updated calendar
        run: |
          python generate_calendar.py

      - name: Commit and push calendar changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.html volunteer_schedule.yaml volunteer_schedule.json || echo "No changes"
          git commit -m "Update volunteer calendar [skip ci]" || echo "No changes to commit"
          git push
